export const ERROR = 'ERROR';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const UPDATE_FLAGS = 'UPDATE_FLAGS';
export const UPDATE_UI = 'UPDATE_UI';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
