export const ERROR = 'ERROR';
export const REDIRECT = 'REDIRECT';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const UPDATE_FLAGS = 'UPDATE_FLAGS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_UI = 'UPDATE_UI';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const API_CALL = 'API_CALL';
export const API_INDEX = 'API_INDEX';
export const API_CREATE = 'API_CREATE';
export const API_SHOW = 'API_SHOW';
export const API_UPDATE = 'API_UPDATE';
export const API_DESTROY = 'API_DESTROY';

export const DISPATCH_MULTIPLE_ACTIONS = 'DISPATCH_MULTIPLE_ACTIONS';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const POP_NOTIFICATION = 'POP_NOTIFICATION';
export const FADE_OUT_NOTIFICATION = 'FADE_OUT_NOTIFICATION';
